name: pin
description: "Package containing all necessary backend logic for implementing PIN code feature in Flutter applications. And even more..."
version: 0.3.2
repository: https://github.com/AndreySosnovyy/flutter_pin_code
issue_tracker: https://github.com/AndreySosnovyy/flutter_pin_code/issues
topics: [pin, pin-code, security, biometrics, face-id]

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

flutter:
  plugin:
    platforms:
      android:
        default_package: local_auth_android
      ios:
        default_package: local_auth_darwin
      macos:
        default_package: local_auth_darwin
      windows:
        default_package: local_auth_windows

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  local_auth: ^2.3.0
  local_auth_android: ^1.0.53
  local_auth_darwin: ^1.6.0
  shared_preferences: ^2.5.3
  local_auth_windows: ^1.0.11
  logger: ^2.6.1

dev_dependencies:
  flutter_lints: ^6.0.0
